name: Make release tag

on:
  push:
    branches:
      - main

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: git checkout artifacts
      - run: git branch artifacts_copy
      - run: git branch --delete artifacts
      - run: git checkout -b artifacts
      - run: git cherry-pick artifacts_copy
      - run: git branch --delete artifacts_copy
      - run: git push --force
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
