name: Make release tag

on:
  push:
    branches:
      - artifacts-*

jobs:
  release-on-push:
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: get next version
        id: "bump"
        uses: allegro-actions/next-version@v1
      - run: |
          set -x
          assets=()
          for asset in ./*.zip; do
            assets+=("-a" "$asset")
          done
          tag_name="${GITHUB_REF##*/}"
          hub release create "${assets[@]}" -m "${{ steps.bump.outputs.next_tag }}" "${{ steps.bump.outputs.next_tag }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update Package.swift
        run: |
          function replaceURL {
            BASE_URL="https:\/\/github.com\/HedvigInsurance\/OdysseyKit\/releases\/download\/$1"
            sed -i '' "s/url: \".*\",\/\/ $2 URL/url: \"$BASE_URL\/$2.xcframework.zip\",\/\/ $2 URL/g" Package.swift
          }

          replaceURL "${{ steps.bump.outputs.next_tag }}" "Odyssey"
          replaceURL "${{ steps.bump.outputs.next_tag }}" "OdysseyKit"
          replaceURL "${{ steps.bump.outputs.next_tag }}" "KMPNativeCoroutinesCore"
          replaceURL "${{ steps.bump.outputs.next_tag }}" "KMPNativeCoroutinesAsync"
          replaceURL "${{ steps.bump.outputs.next_tag }}" "SVGView"
          replaceURL "${{ steps.bump.outputs.next_tag }}" "UIPilot"
          replaceURL "${{ steps.bump.outputs.next_tag }}" "FlexboxSwiftUI"
          replaceURL "${{ steps.bump.outputs.next_tag }}" "FlexboxSwiftUIObjC"
          replaceURL "${{ steps.bump.outputs.next_tag }}" "Placement"
          replaceURL "${{ steps.bump.outputs.next_tag }}" "Yoga"
      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: Package.swift
          commit-msg: Update Package.swift
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
