name: Make release tag

on:
  push:
    branches:
      - artifacts-*

jobs:
  release-on-push:
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: MeilCli/bump-release-action@v1
        id: bump
        with:
          dry_run: true
      - run: |
          set -x
          assets=()
          for asset in ./*.zip; do
            assets+=("-a" "$asset")
          done
          tag_name="${GITHUB_REF##*/}"
          hub release create "${assets[@]}" -m "${{ steps.bump.outputs.next_version }}" "${{ steps.bump.outputs.next_version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update Package.swift
        run: |
          function replaceURL {
            BASE_URL="https:\/\/github.com\/HedvigInsurance\/OdysseyKit\/releases\/download\/$1"
            sed -i '' "s/url: \".*\",\/\/ $2 URL/url: \"$BASE_URL\/$2.xcframework.zip\",\/\/ $2 URL/g" Package.swift
          }

          replaceURL "${{ steps.bump.outputs.next_version }}" "Odyssey"
          replaceURL "${{ steps.bump.outputs.next_version }}" "OdysseyKit"
          replaceURL "${{ steps.bump.outputs.next_version }}" "KMPNativeCoroutinesCore"
          replaceURL "${{ steps.bump.outputs.next_version }}" "KMPNativeCoroutinesAsync"
          replaceURL "${{ steps.bump.outputs.next_version }}" "SVGView"
          replaceURL "${{ steps.bump.outputs.next_version }}" "UIPilot"
      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: Package.swift
          commit-msg: Update Package.swift
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
      - name: Delete branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branches: ${{ github.head_ref }}
