name: Make release tag

on:
  push:
    branches:
      - artifacts-*

jobs:
  release-on-push:
    runs-on: macos-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
          id: previoustag
          uses: "WyriHaximus/github-action-get-previous-tag@v1"
          env:
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - name: 'Get next major version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.previoustag.outputs.tag }}
      - run: |
          set -x
          assets=()
          for asset in ./*.zip; do
            assets+=("-a" "$asset")
          done
          tag_name="${GITHUB_REF##*/}"
          hub release create "${assets[@]}" -m "${{ steps.semvers.outputs.v_major }}" "${{ steps.semvers.outputs.v_major }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update Package.swift
        run: |
          function replaceURL {
            BASE_URL="https:\/\/github.com\/HedvigInsurance\/OdysseyKit\/releases\/download\/$1"
            sed -i "s/url: \".*\",\/\/ $2 URL/url: \"$BASE_URL\/$2.xcframework.zip\",\/\/ $2 URL/g" Package.swift
          }

          replaceURL "${{ steps.semvers.outputs.v_major }}" "Odyssey"
          replaceURL "${{ steps.semvers.outputs.v_major }}" "OdysseyKit"
          replaceURL "${{ steps.semvers.outputs.v_major }}" "KMPNativeCoroutinesCore"
          replaceURL "${{ steps.semvers.outputs.v_major }}" "KMPNativeCoroutinesAsync"
          replaceURL "${{ steps.semvers.outputs.v_major }}" "SVGView"
          replaceURL "${{ steps.semvers.outputs.v_major }}" "UIPilot"
          replaceURL "${{ steps.semvers.outputs.v_major }}" "FlexboxSwiftUI"
          replaceURL "${{ steps.semvers.outputs.v_major }}" "FlexboxSwiftUIObjC"
          replaceURL "${{ steps.semvers.outputs.v_major }}" "Placement"
          replaceURL "${{ steps.semvers.outputs.v_major }}" "Yoga"
      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: Package.swift
          commit-msg: Update Package.swift
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
