name: Make release tag

on:
  push:
    branches:
      - main

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git checkout artifacts
      - run: git branch artifacts_copy
      - run: git checkout artifacts_copy
      - run: git branch --delete artifacts
      - run: git checkout -b artifacts
      - run: git config --global user.email "ios@hedvig.com"
      - run: git config --global user.name "Hedvig iOS"
      - run: git cherry-pick artifacts_copy --strategy-option=theirs
      - run: git branch --delete artifacts_copy
      - run: git push --force
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
